version: '2'
services:
 labkey-application-§§INSTANCE:
  image: bibbox/labkey
  container_name: labkey-§§INSTANCE
  links:
  - labkeydb-§§INSTANCE
  ports:
  - §§PORT:8080
  environment:
  - POSTGRES_PASSWORD=§§SET_PGSETUP_POSTGRES_PASSWORD
  - SMTP_HOST=@@smtpHost@@
  - SMTP_USER=@@smtpUser@@
  - SMTP_PORT=@@smtpPort@@
  depends_on:
  - labkey-db-§§INSTANCE
 labkey-db-§§INSTANCE:
  image: postgres:9.5
  container_name: labkey-db-§§INSTANCE
  environment:
  - POSTGRES_PASSWORD=§§SET_PGSETUP_POSTGRES_PASSWORD
  - POSTGRES_USER=labkey
  - PGDATA=/var/lib/postgresql/data/pgdata
  - POSTGRES_DB=lportal
  