version: '2'
services:
  openspecimen-gradle-§§INSTANCE:
    image: bibbox/openspecimen-gradle
    container_name: openspecimen-gradle-§§INSTANCE
    environment:
      - RELEASEURL=§§RELEASEURL
      - TOMCATPATH=§§TOMCATPATH
      - INSTANCE=§§INSTANCE
      - MYSQL_DATABASE=openspecimen
      - MYSQL_USER=openspecimen
      - MYSQL_PASSWORD=openspecimen
  openspecimen-web-§§INSTANCE:
    image: bibbox/openspecimen
    container_name: openspecimen-web-§§INSTANCE
    links:
      - openspecimen-db-§§INSTANCE:openspecimen-db-§§INSTANCE
    ports:
     - "8098:8080"
    depends_on:
     - openspecimen-db-§§INSTANCE
     - openspecimen-data-§§INSTANCE
  openspecimen-db-§§INSTANCE:
    image: mysql
    container_name: openspecimen-db-§§INSTANCE
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=openspecimen
      - MYSQL_DATABASE=openspecimen
      - MYSQL_USER=openspecimen
      - MYSQL_PASSWORD=openspecimen
    volumes_from: 
      - openspecimen-data-§§INSTANCE
    depends_on:
     - openspecimen-data-§§INSTANCE
  openspecimen-data-§§INSTANCE:
    image: bibbox/openspecimen-data
    container_name: openspecimen-data-§§INSTANCE
    volumes:
      - /opt/openspecimen/var/lib/mysql:/var/lib/mysql
      - /opt/openspecimen/etc/mysql/conf.d/openspecimen.cnf:/etc/mysql/conf.d/openspecimen.cnf