version: '2'
services:
  OpenLdap-application-§§INSTANCE:
    image: bibbox/OpenLdap-application
    container_name: OpenLdap-application-§§INSTANCE
    volumes_from:
      - OpenLdap-data-§§INSTANCE
    ports:
      - §§PORT:8080
    environment:
      - SLAPD_PASSWORD=§§SLAPD_PASSWORD
    depends_on:
      - OpenLdap-data-§§INSTANCE
  phpldapadmin-§§INSTANCE:
    image: bibbox/phpldapadmin
    container_name: phpldapadmin-§§INSTANCE
    volumes_from:
      - OpenLdap-data-§§INSTANCE
    ports:
      - §§PORT:8080
    environment:
      - 
    depends_on:
      - OpenLdap-data-§§INSTANCE
      - OpenLdap-application-§§INSTANCE
  OpenLdap-data-§§INSTANCE:
    image: bibbox/bibbox-data
    container_name: OpenLdap-data-§§INSTANCE
    volumes:
      - §§FOLDER/var/lib/ldap:/var/lib/ldap