version: '2'
services:
  molgenis-web:
    image: bibbox/molgenis
    links:
      - molgenis-mysql:molgenisdb
    ports:
     - "7777:8080"
    environment:
     - MOLGENIS_ADMIN_PASSWORD=molgenis
     - MOLGENIS_ADMIN_email=robert.reihs@gmail.com
    depends_on:
     - molgenis-mysql
  molgenis-mysql:
    image: mysql
    user: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=molgenis
      - MYSQL_USER=molgenis
      - MYSQL_PASSWORD=molgenis
    volumes:
      - /var/lib/mysql
