version: '2'
services:
  molgenis-web:
    image: bibbox/molgenis
    links:
      - molgenis-mysql
    ports:
     - "${MOLGENIS_PORT}:8080"
    depends_on:
     - molgenis-mysql
  molgenis-mysql:
    image: mysql
    user: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD}
  volumes:
    - /var/lib/mysql
