version: '2'
services:
  elasticsearch-bibbox:
    image: elasticsearch
    container_name: elasticsearch-bibbox
    volumes_from:
      - elasticsearchData
    ports:
      - "9200:9200"
      
  logstash-bibbox:
    image: logstash
    container_name: logstash-bibbox
    environment:
      TZ: Europe/Vienna
    ports:
      - "12201:12201/udp"
    volumes:
      - ./config:/config
    links:
      - elasticsearch-bibbox
    command: logstash -f /config/gelf.conf
    
  kibana-bibbox:
    image: kibana
    container_name: kibana-bibbox
    ports:
      - "5601:5601"
    links:
      - elasticsearch-bibbox

  elasticsearchData:
    image: busybox
    command: "true"
    volumes:
        - /usr/share/elasticsearch/data