version: '2'
services:
  elasticsearch:
    image: elasticsearch:latest
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: kibana:latest
    container_name: kibana
    ports:
      - "5000:5000"
    links:
      - elasticsearch
  logstash:
    image: logstash:latest
    container_name: logstash
    ports:
      - "5601:5601"
    links:
      - elasticsearch